name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        dotnet-version: [ 7.0.x ]

    name: Build
    runs-on: ${{ matrix.platform }}
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
        
      - name: Add Env Property
        run: |
          echo "VERSION=`echo ${GITHUB_REF/refs\/tags\//}`" >> $GITHUB_ENV
          export LANG=zh_CN.UTF-8

      - name: Build
        run: |
            dotnet publish -c Release --no-self-contained -f net7.0-windows \
            -r win-x64 -p:PublishSingleFile=true -p:EnableWindowsTargeting=true \
            -property:PublishDir=./publish \
            -p:Version=${VERSION#v}

      - name: Compress
        run: |
          cd ./X-OTP/publish/
          zip -r ${{ github.workspace }}/X-OTP.zip ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: X-OTP
            path: ${{ github.workspace }}/X-OTP/publish

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Full
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: X-OTP.zip
          asset_name: X-OTP-${{ env.VERSION }}.zip
          asset_content_type: application/zip
